customhost = "employeetest.c94kgmk4k67f.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin3005"
customdb = "employee"
custombucket = "employeebucketvipin"
customregion = "ap-south-1"
customtable = "employee"
